codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project: off
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**.md"
  - ".github"
  - ".vscode"
  - "build"
  - "docs"
  - "examples"
  - "src/Shared"
  - "test"

flags:
  unittests-Solution-Stable:
    carryforward: true
    paths:
      - src

  unittests-Solution-Experimental:
    carryforward: true
    paths:
      - src

  unittests-Instrumentation-Stable:
    carryforward: true
    paths:
      - src

  unittests-Instrumentation-Experimental:
    carryforward: true
    paths:
      - src
