
// <auto-generated/>
using System;
using System.Net.Http;
using OpenTelemetry.Exporter.LightStep.Implementation;
using OpenTelemetry.Trace.Export;

namespace OpenTelemetry.Exporter.LightStep
{
    public class LightStepTraceExporter
    {
        private const string ExporterName = "LightStepExporter";
        private readonly LightStepTraceExporterOptions options;
        private readonly ISpanExporter exporter;
        private readonly object _lock = new object();
        private readonly HttpClient httpClient;
        private TraceExporterHandler handler;

        public LightStepTraceExporter(LightStepTraceExporterOptions options, ISpanExporter exporter,
            HttpClient client = null)
        {
            this.options = options;
            this.exporter = exporter;
            this.httpClient = client;
        }

        public void Start()
        {
            lock (this._lock)
            {
                if (this.handler != null)
                {
                    return;
                }
                this.handler = new TraceExporterHandler(this.options, this.httpClient);
                
                this.exporter.RegisterHandler(ExporterName, this.handler);
            }
        }

        public void Stop()
        {
            lock (this._lock)
            {
                if (this.handler == null)
                {
                    return;
                }
                
                this.exporter.UnregisterHandler(ExporterName);
                this.handler = null;
            }
        }
    }
}
