# CI build. No publishing of artifacts.

variables:
  DotNetVersion: "3.1.101"

# A pipeline with no CI trigger
trigger: none

pr: [ 'master' ]

jobs:

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: force use of desired dotnet version
    inputs:
      version: $(DotNetVersion)

  # "restore" is run automatically by "build"
  - task: VSBuild@1
    displayName: build solution using VS (Release)
    inputs:
      solution: OpenTelemetry.proj
      vsVersion: "latest"
      platform: "AnyCPU"
      configuration: "Release"
      msbuildArgs: "/p:OS=$(Agent.OS)"

  # consider switch to https://docs.microsoft.com/vsts/pipelines/tasks/test/vstest?view=vsts
  - task: DotNetCoreCLI@2
    displayName: test using CLI
    inputs:
      command: "test"
      projects: |
        test/**/*.Tests.csproj
        test/**/*.Tests.Win.csproj
      arguments: "-p:CollectCoverage=false --configuration Release"

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: force use of desired dotnet version
    inputs:
      version: $(DotNetVersion)

  # "restore" is run automatically by "build"
  - task: DotNetCoreCLI@2
    displayName: build solution using CLI (Release)
    inputs:
      command: "build"
      projects: OpenTelemetry.proj
      arguments: "-p:OS=$(Agent.OS) --configuration Release"

  - task: DotNetCoreCLI@2
    displayName: test using CLI
    inputs:
      command: "test"
      projects: "test/**/*.Tests.csproj"
      arguments: "-p:CollectCoverage=false --configuration Release"
