// <auto-generated/>

using OpenTelemetry.Trace.Configuration;
using OpenTelemetry.Exporter.Console;
using OpenTelemetry.Trace;

namespace Samples
{
    internal class TestConsole
    {
        internal static object Run()
        {
            // create exporter
            var exporter = new ConsoleExporter();

            // Create tracer
            using (var tracerFactory = TracerFactory.Create(builder => {
                builder.AddProcessorPipeline(p => p.SetExporter(exporter));
            }))
            {
                var tracer = tracerFactory.GetTracer("logging-test");

                using (tracer.StartActiveSpan("parent", out var parent))
                {
                    using (tracer.StartActiveSpan("child", out var child))
                    {
                        child.SetAttribute("key", "value");
                    }
                }

                return null;
            }
        }
    }
}
