// <auto-generated/>

using Microsoft.Extensions.Logging;
using OpenTelemetry.Trace.Configuration;
using OpenTelemetry.Exporter.Logging;
using OpenTelemetry.Trace;

namespace Samples
{
    internal class TestLogging
    {
        internal static object Run()
        {
            // create logger
            var loggerFactory = LoggerFactory.Create(builder =>
            {
                builder.AddConsole();
            });
            var logger = loggerFactory.CreateLogger<TestLogging>();

            // create exporter
            var exporter = new LoggingExporter(logger, new LoggingExporterOptions());

            // Create tracer
            using (var tracerFactory = TracerFactory.Create(builder => {
                builder.AddProcessorPipeline(p => p.SetExporter(exporter));
            }))
            {
                var tracer = tracerFactory.GetTracer("logging-test");

                using (tracer.StartActiveSpan("parent", out var parent))
                {
                    using (tracer.StartActiveSpan("child", out var child))
                    {
                        child.SetAttribute("key", "value");
                    }
                }

                return null;
            }
        }
    }
}
