name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure to fill out the entire form below, providing as much context as you can in order to help us triage and track down your bug as quickly as possible.

        Before filing a bug, please be sure you have searched through [existing bugs](https://github.com/open-telemetry/opentelemetry-dotnet/issues?q=is%3Aissue+is%3Aopen+label%3Abug) to see if an existing issue covers your bug.

  - type: dropdown
    id: area
    attributes:
      label: Area(s)
      description: Which area(s) does your bug report concern? If none fits, please select `area:other`
      multiple: true
      options:
        - area:api
        - area:exporter
        - area:exporter:otlp
        - area:exporter:prometheus
        - area:ext:hosting
        - area:other
        - area:sdk

  - type: textarea
    attributes:
      label: Package version
      description: List of [all OpenTelemetry NuGet packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are using (e.g. `OpenTelemetry 1.0.2`)
      value: |
        | Package Name                          | Version |
        | ------------------------------------- | ------- |
        | OpenTelemetry.Api                     | 1.8.0   |
        | OpenTelemetry                         | 1.8.0   |
        | TBD                                   | TBD     |
    validations:
      required: true

  - type: input
    attributes:
      label: Runtime version
      description: What .NET runtime version (e.g. `net462`, `net48`, `netcoreapp3.1`, `net6.0` etc. You can find this information from the `*.csproj` file) did you use?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened?
      description: Please provide as much detail as you reasonably can.
      value: |
        ## Description

        ## Steps to Reproduce

        Create a self-contained project using the template of your choice, apply the minimum required code to result in the issue you're observing.

        We will close this issue if:

        * The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
        * If we can not reproduce the behavior you're reporting.

        ## Expected Result

        ## Actual Result

    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.
