name: Question
description: Ask a question to help us improve our knowledge base and documentation
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Please ask questions using [GitHub Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new) instead of GitHub Issues.

  - type: textarea
    attributes:
      label: What is the question?
      description: Describe the question you have.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this question.
