name: Question
description: Ask a question to help us improve our knowledge base and documentation
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Please use [GitHub Discussions](https://github.com/open-telemetry/opentelemetry-dotnet/discussions/new).
