<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworksForLibraries)</TargetFrameworks>
    <Description>Console exporter for OpenTelemetry .NET</Description>
    <PackageTags>$(PackageTags);Console;distributed-tracing</PackageTags>
    <MinVerTagPrefix>core-</MinVerTagPrefix>
    <ReferenceSystemTextJsonPackages>true</ReferenceSystemTextJsonPackages>
    <SupportsBrowserAndMobilePlatforms>true</SupportsBrowserAndMobilePlatforms>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn),CS1591</NoWarn>
  </PropertyGroup>

  <!-- This package is explicitly upgraded for .NET 8 to fix native AoT compatibility issues -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" VersionOverride="8.0.2" Condition="'$(TargetFramework)' == 'net8.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)\src\OpenTelemetry\OpenTelemetry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(RepoRoot)\src\Shared\Metrics\Base2ExponentialBucketHistogramHelper.cs" Link="Includes\Metrics\Base2ExponentialBucketHistogramHelper.cs" />
    <Compile Include="$(RepoRoot)\src\Shared\PeriodicExportingMetricReaderHelper.cs" Link="Includes\PeriodicExportingMetricReaderHelper.cs" />
    <Compile Include="$(RepoRoot)\src\Shared\TagWriter\*.cs" Link="Includes\TagWriter\%(Filename).cs" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenTelemetry.Exporter.Console.Tests" PublicKey="$(StrongNamePublicKey)" />
  </ItemGroup>

</Project>
