// <copyright file="DestinationAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>destination</c> namespace.
    /// </summary>
    public static class DestinationAttributes
    {
        /// <summary>
        /// Destination address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
        /// </summary>
        /// <remarks>
        /// When observed from the source side, and when communicating through an intermediary, <c>destination.address</c> SHOULD represent the destination address behind any intermediaries, for example proxies, if it&amp;#39;s available.
        /// </remarks>
        public const string DestinationAddress = "destination.address";

        /// <summary>
        /// Destination port number.
        /// </summary>
        public const string DestinationPort = "destination.port";
    }
}