// <copyright file="GraphqlAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>graphql</c> namespace.
    /// </summary>
    public static class GraphqlAttributes
    {
        /// <summary>
        /// The GraphQL document being executed.
        /// </summary>
        /// <remarks>
        /// The value may be sanitized to exclude sensitive information.
        /// </remarks>
        public const string GraphqlDocument = "graphql.document";

        /// <summary>
        /// The name of the operation being executed.
        /// </summary>
        public const string GraphqlOperationName = "graphql.operation.name";

        /// <summary>
        /// The type of the operation being executed.
        /// </summary>
        public const string GraphqlOperationType = "graphql.operation.type";

        /// <summary>
        /// The type of the operation being executed.
        /// </summary>
        public static class GraphqlOperationTypeValues
        {
            /// <summary>
            /// GraphQL query.
            /// </summary>
            public const string Query = "query";
            /// <summary>
            /// GraphQL mutation.
            /// </summary>
            public const string Mutation = "mutation";
            /// <summary>
            /// GraphQL subscription.
            /// </summary>
            public const string Subscription = "subscription";
        }
    }
}