// <copyright file="IosAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>ios</c> namespace.
    /// </summary>
    public static class IosAttributes
    {
        /// <summary>
        /// This attribute represents the state the application has transitioned into at the occurrence of the event.
        /// </summary>
        /// <remarks>
        /// The iOS lifecycle states are defined in the <a href="https://developer.apple.com/documentation/uikit/uiapplicationdelegate#1656902">UIApplicationDelegate documentation</a>, and from which the <c>OS terminology</c> column values are derived.
        /// </remarks>
        public const string IosState = "ios.state";

        /// <summary>
        /// This attribute represents the state the application has transitioned into at the occurrence of the event.
        /// </summary>
        public static class IosStateValues
        {
            /// <summary>
            /// The app has become <c>active</c>. Associated with UIKit notification <c>applicationDidBecomeActive</c>.
            /// </summary>
            public const string Active = "active";
            /// <summary>
            /// The app is now <c>inactive</c>. Associated with UIKit notification <c>applicationWillResignActive</c>.
            /// </summary>
            public const string Inactive = "inactive";
            /// <summary>
            /// The app is now in the background. This value is associated with UIKit notification <c>applicationDidEnterBackground</c>.
            /// </summary>
            public const string Background = "background";
            /// <summary>
            /// The app is now in the foreground. This value is associated with UIKit notification <c>applicationWillEnterForeground</c>.
            /// </summary>
            public const string Foreground = "foreground";
            /// <summary>
            /// The app is about to terminate. Associated with UIKit notification <c>applicationWillTerminate</c>.
            /// </summary>
            public const string Terminate = "terminate";
        }
    }
}