// <copyright file="MessageAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>message</c> namespace.
    /// </summary>
    public static class MessageAttributes
    {
        /// <summary>
        /// Compressed size of the message in bytes.
        /// </summary>
        public const string MessageCompressedSize = "message.compressed_size";

        /// <summary>
        /// MUST be calculated as two different counters starting from <c>1</c> one for sent messages and one for received message.
        /// </summary>
        /// <remarks>
        /// This way we guarantee that the values will be consistent between different implementations.
        /// </remarks>
        public const string MessageId = "message.id";

        /// <summary>
        /// Whether this is a received or sent message.
        /// </summary>
        public const string MessageType = "message.type";

        /// <summary>
        /// Uncompressed size of the message in bytes.
        /// </summary>
        public const string MessageUncompressedSize = "message.uncompressed_size";

        /// <summary>
        /// Whether this is a received or sent message.
        /// </summary>
        public static class MessageTypeValues
        {
            /// <summary>
            /// sent.
            /// </summary>
            public const string Sent = "SENT";
            /// <summary>
            /// received.
            /// </summary>
            public const string Received = "RECEIVED";
        }
    }
}