// <copyright file="NetworkAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>network</c> namespace.
    /// </summary>
    public static class NetworkAttributes
    {
        /// <summary>
        /// The ISO 3166-1 alpha-2 2-character country code associated with the mobile carrier network.
        /// </summary>
        public const string NetworkCarrierIcc = "network.carrier.icc";

        /// <summary>
        /// The mobile carrier country code.
        /// </summary>
        public const string NetworkCarrierMcc = "network.carrier.mcc";

        /// <summary>
        /// The mobile carrier network code.
        /// </summary>
        public const string NetworkCarrierMnc = "network.carrier.mnc";

        /// <summary>
        /// The name of the mobile carrier.
        /// </summary>
        public const string NetworkCarrierName = "network.carrier.name";

        /// <summary>
        /// This describes more details regarding the connection.type. It may be the type of cell technology connection, but it could be used for describing details about a wifi connection.
        /// </summary>
        public const string NetworkConnectionSubtype = "network.connection.subtype";

        /// <summary>
        /// The internet connection type.
        /// </summary>
        public const string NetworkConnectionType = "network.connection.type";

        /// <summary>
        /// This describes more details regarding the connection.type. It may be the type of cell technology connection, but it could be used for describing details about a wifi connection.
        /// </summary>
        public static class NetworkConnectionSubtypeValues
        {
            /// <summary>
            /// GPRS.
            /// </summary>
            public const string Gprs = "gprs";
            /// <summary>
            /// EDGE.
            /// </summary>
            public const string Edge = "edge";
            /// <summary>
            /// UMTS.
            /// </summary>
            public const string Umts = "umts";
            /// <summary>
            /// CDMA.
            /// </summary>
            public const string Cdma = "cdma";
            /// <summary>
            /// EVDO Rel. 0.
            /// </summary>
            public const string Evdo0 = "evdo_0";
            /// <summary>
            /// EVDO Rev. A.
            /// </summary>
            public const string EvdoA = "evdo_a";
            /// <summary>
            /// CDMA2000 1XRTT.
            /// </summary>
            public const string Cdma20001xrtt = "cdma2000_1xrtt";
            /// <summary>
            /// HSDPA.
            /// </summary>
            public const string Hsdpa = "hsdpa";
            /// <summary>
            /// HSUPA.
            /// </summary>
            public const string Hsupa = "hsupa";
            /// <summary>
            /// HSPA.
            /// </summary>
            public const string Hspa = "hspa";
            /// <summary>
            /// IDEN.
            /// </summary>
            public const string Iden = "iden";
            /// <summary>
            /// EVDO Rev. B.
            /// </summary>
            public const string EvdoB = "evdo_b";
            /// <summary>
            /// LTE.
            /// </summary>
            public const string Lte = "lte";
            /// <summary>
            /// EHRPD.
            /// </summary>
            public const string Ehrpd = "ehrpd";
            /// <summary>
            /// HSPAP.
            /// </summary>
            public const string Hspap = "hspap";
            /// <summary>
            /// GSM.
            /// </summary>
            public const string Gsm = "gsm";
            /// <summary>
            /// TD-SCDMA.
            /// </summary>
            public const string TdScdma = "td_scdma";
            /// <summary>
            /// IWLAN.
            /// </summary>
            public const string Iwlan = "iwlan";
            /// <summary>
            /// 5G NR (New Radio).
            /// </summary>
            public const string Nr = "nr";
            /// <summary>
            /// 5G NRNSA (New Radio Non-Standalone).
            /// </summary>
            public const string Nrnsa = "nrnsa";
            /// <summary>
            /// LTE CA.
            /// </summary>
            public const string LteCa = "lte_ca";
        }

        /// <summary>
        /// The internet connection type.
        /// </summary>
        public static class NetworkConnectionTypeValues
        {
            /// <summary>
            /// wifi.
            /// </summary>
            public const string Wifi = "wifi";
            /// <summary>
            /// wired.
            /// </summary>
            public const string Wired = "wired";
            /// <summary>
            /// cell.
            /// </summary>
            public const string Cell = "cell";
            /// <summary>
            /// unavailable.
            /// </summary>
            public const string Unavailable = "unavailable";
            /// <summary>
            /// unknown.
            /// </summary>
            public const string Unknown = "unknown";
        }
    }
}