// <copyright file="OsAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>os</c> namespace.
    /// </summary>
    public static class OsAttributes
    {
        /// <summary>
        /// Unique identifier for a particular build or compilation of the operating system.
        /// </summary>
        public const string OsBuildId = "os.build_id";

        /// <summary>
        /// Human readable (not intended to be parsed) OS version information, like e.g. reported by <c>ver</c> or <c>lsb_release -a</c> commands.
        /// </summary>
        public const string OsDescription = "os.description";

        /// <summary>
        /// Human readable operating system name.
        /// </summary>
        public const string OsName = "os.name";

        /// <summary>
        /// The operating system type.
        /// </summary>
        public const string OsType = "os.type";

        /// <summary>
        /// The version string of the operating system as defined in <a href="/docs/resource/README.md#version-attributes">Version Attributes</a>.
        /// </summary>
        public const string OsVersion = "os.version";

        /// <summary>
        /// The operating system type.
        /// </summary>
        public static class OsTypeValues
        {
            /// <summary>
            /// Microsoft Windows.
            /// </summary>
            public const string Windows = "windows";
            /// <summary>
            /// Linux.
            /// </summary>
            public const string Linux = "linux";
            /// <summary>
            /// Apple Darwin.
            /// </summary>
            public const string Darwin = "darwin";
            /// <summary>
            /// FreeBSD.
            /// </summary>
            public const string Freebsd = "freebsd";
            /// <summary>
            /// NetBSD.
            /// </summary>
            public const string Netbsd = "netbsd";
            /// <summary>
            /// OpenBSD.
            /// </summary>
            public const string Openbsd = "openbsd";
            /// <summary>
            /// DragonFly BSD.
            /// </summary>
            public const string Dragonflybsd = "dragonflybsd";
            /// <summary>
            /// HP-UX (Hewlett Packard Unix).
            /// </summary>
            public const string Hpux = "hpux";
            /// <summary>
            /// AIX (Advanced Interactive eXecutive).
            /// </summary>
            public const string Aix = "aix";
            /// <summary>
            /// SunOS, Oracle Solaris.
            /// </summary>
            public const string Solaris = "solaris";
            /// <summary>
            /// IBM z/OS.
            /// </summary>
            public const string ZOs = "z_os";
        }
    }
}