// <copyright file="OtelAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>otel</c> namespace.
    /// </summary>
    public static class OtelAttributes
    {
        /// <summary>
        /// The name of the instrumentation scope - (<c>InstrumentationScope.Name</c> in OTLP).
        /// </summary>
        public const string OtelScopeName = "otel.scope.name";

        /// <summary>
        /// The version of the instrumentation scope - (<c>InstrumentationScope.Version</c> in OTLP).
        /// </summary>
        public const string OtelScopeVersion = "otel.scope.version";

        /// <summary>
        /// Name of the code, either &quot;OK&quot; or &quot;ERROR&quot;. MUST NOT be set if the status code is UNSET.
        /// </summary>
        public const string OtelStatusCode = "otel.status_code";

        /// <summary>
        /// Description of the Status if it has a value, otherwise not set.
        /// </summary>
        public const string OtelStatusDescription = "otel.status_description";

        /// <summary>
        /// Name of the code, either &quot;OK&quot; or &quot;ERROR&quot;. MUST NOT be set if the status code is UNSET.
        /// </summary>
        public static class OtelStatusCodeValues
        {
            /// <summary>
            /// The operation has been validated by an Application developer or Operator to have completed successfully.
            /// </summary>
            public const string Ok = "OK";
            /// <summary>
            /// The operation contains an error.
            /// </summary>
            public const string Error = "ERROR";
        }
    }
}