// <copyright file="PoolAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>pool</c> namespace.
    /// </summary>
    public static class PoolAttributes
    {
        /// <summary>
        /// The name of the connection pool; unique within the instrumented application. In case the connection pool implementation doesn't provide a name, then the <a href="/docs/database/database-spans.md#connection-level-attributes">db.connection_string</a> should be used.
        /// </summary>
        public const string PoolName = "pool.name";
    }
}