// <copyright file="WebengineAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions.v1_23_1_Experimental
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>webengine</c> namespace.
    /// </summary>
    public static class WebengineAttributes
    {
        /// <summary>
        /// Additional description of the web engine (e.g. detailed version and edition information).
        /// </summary>
        public const string WebengineDescription = "webengine.description";

        /// <summary>
        /// The name of the web engine.
        /// </summary>
        public const string WebengineName = "webengine.name";

        /// <summary>
        /// The version of the web engine.
        /// </summary>
        public const string WebengineVersion = "webengine.version";
    }
}