services:

  # OTEL Collector to receive logs, metrics and traces from the application
  # plus a UI to query logs, traces and metrics and visualize them.
  otel-lgtm:
    image: grafana/otel-lgtm:0.23.0@sha256:dde2dcd51e955e27e1ab454e6ba8e6f8c958e7d22dca1d4ab0be87fa64198051

    ports:
      - 3000:3000 # UI
      - 4317:4317 # OTLP over gRPC for logs, metrics and traces
      - 4318:4318 # OTLP over HTTP for logs, metrics and traces
      - 9090:9090 # Prometheus
