// <auto-generated/>
namespace OpenTelemetry.Exporter.LightStep.Implementation
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    
    internal class LightStepReport
    {
        [JsonProperty("auth")]
        public Authentication Auth { get; set; }
        
        [JsonProperty("reporter")]
        public Reporter Reporter { get; set; }
        [JsonProperty("spans")]
        public IList<LightStepSpan> Spans { get; set; } = new List<LightStepSpan>();
    }

    internal class Authentication
    {
        [JsonProperty("access_token")]
        public string AccessToken { get; set; }
    }

    internal class Reporter
    {
        [JsonProperty("reporter_id")]
        public int ReporterId { get; set; }
        
        [JsonProperty("tags")]
        public IList<Tag> Tags { get; set; } = new List<Tag>();
    }
}
