// <copyright file="ClientAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>client</c> namespace.
    /// </summary>
    public static class ClientAttributes
    {
        /// <summary>
        /// Client address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
        /// </summary>
        /// <remarks>
        /// When observed from the server side, and when communicating through an intermediary, <c>client.address</c> SHOULD represent the client address behind any intermediaries,  for example proxies, if it&amp;#39;s available.
        /// </remarks>
        public const string ClientAddress = "client.address";

        /// <summary>
        /// Client port number.
        /// </summary>
        /// <remarks>
        /// When observed from the server side, and when communicating through an intermediary, <c>client.port</c> SHOULD represent the client port behind any intermediaries,  for example proxies, if it&amp;#39;s available.
        /// </remarks>
        public const string ClientPort = "client.port";
    }
}