// <copyright file="ServerAttributes.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>

// <auto-generated> This file has been auto generated from buildscripts/semantic-conventions/templates/Attributes.cs.j2</auto-generated>

using System;

namespace OpenTelemetry.SemanticConventions
{
    /// <summary>
    /// Describes semantic conventions for attributes in the <c>server</c> namespace.
    /// </summary>
    public static class ServerAttributes
    {
        /// <summary>
        /// Server domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
        /// </summary>
        /// <remarks>
        /// When observed from the client side, and when communicating through an intermediary, <c>server.address</c> SHOULD represent the server address behind any intermediaries, for example proxies, if it&amp;#39;s available.
        /// </remarks>
        public const string ServerAddress = "server.address";

        /// <summary>
        /// Server port number.
        /// </summary>
        /// <remarks>
        /// When observed from the client side, and when communicating through an intermediary, <c>server.port</c> SHOULD represent the server port behind any intermediaries, for example proxies, if it&amp;#39;s available.
        /// </remarks>
        public const string ServerPort = "server.port";
    }
}