services:
  zipkin:
    image: openzipkin/zipkin:3.6.0@sha256:ebfd47b93879b4bec4075ea3a4b07744c5476bae8dca3f6f9c2aca798ceaf0cc
    ports:
      - 9411:9411

# OpenTelemetry Collector is used to receive traces from the services and export them to Zipkin for visualization.
# You can choose to configure different visualization backends by modifying the otel-collector-config.yaml file.
# Alternatively, you can have the services export traces directly to Zipkin by https://github.com/openzipkin-contrib/zipkin-otel.
  otel-collector:
    image: otel/opentelemetry-collector:0.149.0@sha256:dd56aed607fd02f8ac01dddb27a859c0c2cc750539abce927803778fafc736ae
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4318:4318   # OTLP HTTP/protobuf
    depends_on:
      - zipkin

  rabbitmq:
    image: rabbitmq:4-management-alpine@sha256:43553fb6af12bfcf0ed95fbb1c4c658d2b96eed021daf5153749a35ffb87d13d
    ports:
      - 5672:5672
      - 15672:15672

  webapi:
    build:
      context: ../..
      dockerfile: ./examples/MicroserviceExample/WebApi/Dockerfile
    image: opentelemetry-example-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - OTEL_COLLECTOR_HOSTNAME=otel-collector
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
      - otel-collector

  workerservice:
    build:
      context: ../..
      dockerfile: ./examples/MicroserviceExample/WorkerService/Dockerfile
    image: opentelemetry-example-workerservice
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - OTEL_COLLECTOR_HOSTNAME=otel-collector
    restart: on-failure
    depends_on:
      - rabbitmq
      - otel-collector
