name: Blazor WASM integration tests

on:
  workflow_call:
    inputs:
      trigger:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run-blazor-wasm-integration-test:
    name: Blazor WASM integration tests

    strategy:
      fail-fast: ${{ inputs.trigger == 'merge_group' }}
      matrix:
        os:
          # renovate: datasource=github-runners depType=github-runner
          - ubuntu-24.04
          # renovate: datasource=github-runners depType=github-runner
          - windows-2025
        version: [ net10.0 ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0

    - name: Install wasm-tools workload
      shell: pwsh
      run: dotnet workload install wasm-tools

    - name: Run Blazor WASM end-to-end tests
      shell: pwsh
      run: >
        dotnet test test/OpenTelemetry.BlazorWasm.Tests/OpenTelemetry.BlazorWasm.Tests.csproj
        --configuration Release
        --framework ${env:TARGET_FRAMEWORK}
        --logger:"GitHubActions;report-warnings=false"
      env:
        TARGET_FRAMEWORK: ${{ matrix.version }}

    - name: Upload Playwright artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: blazor-playwright-artifacts-${{ matrix.os }}-${{ matrix.version }}
        path: '**/playwright/**'
        if-no-files-found: ignore
        retention-days: 7
