name: Test publish AOTCompatibility testApp

on:
  push:
    branches: [ 'main*' ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ 'main*' ]
    paths-ignore:
    - '**.md'

jobs:
  install-dependencies:
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net6.0, net7.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetching all

    - name: Install dependencies
      run: dotnet restore

  publish-AOT-testApp:
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: dotnet publish ./test/OpenTelemetry.AotCompatibility.TestApp/OpenTelemetry.AotCompatibility.TestApp.csproj --self-contained -nodeReuse:false /p:UseSharedCompilation=false >> "$GITHUB_OUTPUT"

  assert-publish-AOT-testApp-output:
    needs: publish-AOT-testApp
    run: echo "$GITHUB_OUTPUT $output1"
