name: Dependency Submission (NuGet)

on:
  push:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

jobs:
  submit-nuget:
    name: Submit NuGet dependency snapshot
    if: github.event.repository.fork == false
    runs-on: windows-2025
    timeout-minutes: 10

    permissions:
      contents: write # Submit the generated dependency snapshot to the repository dependency graph
      id-token: write # Authenticate the dependency submission with GitHub OIDC

    steps:
      - name: Update agent configuration
        shell: pwsh
        run: |
          "DOTNET_INSTALL_DIR=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "DOTNET_ROOT=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "NUGET_PACKAGES=D:\.nuget\packages" >> ${env:GITHUB_ENV}

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

      - name: Restore workloads
        run: dotnet workload restore ./OpenTelemetry.Extended.slnx

      - name: Restore NuGet packages
        run: dotnet restore ./OpenTelemetry.Extended.slnx

      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@b282c67b1008fde9b60da4bdfcd8849613e293b2 # v0.1.6
        with:
          detectorsCategories: NuGet
