name: Build docfx

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-docfx-build:
    name: Build docfx
    runs-on: windows-2025

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

    - name: Install docfx
      shell: pwsh
      env:
        # renovate: datasource=nuget depName=docfx
        DOCFX_VERSION: '2.78.5'
      run: dotnet tool install -g docfx --version ${env:DOCFX_VERSION}

    - name: Build docfx
      shell: pwsh
      run: .\build\docfx.cmd
