# Called by ci.yml to perform dotnet format linting
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Lint - dotnet format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-dotnet-format-stable:
    name: Run dotnet format (stable)
    runs-on: windows-2025

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

    - name: dotnet restore
      run: dotnet restore OpenTelemetry.slnx

    - name: dotnet format
      run: dotnet format OpenTelemetry.slnx --no-restore --verify-no-changes # Note: .proj files are currently not supported by dotnet format
      env:
        ExposeExperimentalFeatures: false

  run-dotnet-format-experimental:
    name: Run dotnet format (experimental)
    runs-on: windows-2025

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

    - name: dotnet restore
      run: dotnet restore OpenTelemetry.slnx

    - name: dotnet format
      run: dotnet format OpenTelemetry.slnx --no-restore --verify-no-changes # Note: .proj files are currently not supported by dotnet format
      env:
        ExposeExperimentalFeatures: true
