name: First time contributor

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] Only code from the main branch is executed
    types: [opened]

permissions: {}

jobs:
  welcome:
    permissions:
      pull-requests: write # To post the welcome comment
    uses: open-telemetry/shared-workflows/.github/workflows/first-time-pr.yml@ad1959372f2919fcf2556d3a3d12ed5265c54209 # v0.16.0
