name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  fossa:
    name: Run FOSSA scan
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Run FOSSA analysis
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          team: OpenTelemetry
