# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

# Description: This workflow exists to unblock documentation-only PRs.

# IMPORTANT: This workflow MUST use the same 'name' and 'matrix' as the non -md workflow.

name: Integration Tests

on:
  pull_request:
    branches: [ 'main*' ]
    paths:
    - '**.md'

jobs:
  sql-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [net6.0,net7.0]
    steps:
      - run: 'echo "No build required"'

  w3c-trace-context-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [net6.0,net7.0]
    steps:
      - run: 'echo "No build required"'

  otlp-exporter-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [net6.0,net7.0]
    steps:
      - run: 'echo "No build required"'
