name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "24 5 * * 0" # Once a week
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  analysis:
    name: Scorecard analysis
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.event.repository.fork == false)
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@68c7b2f0ef9cd9c1e2b71d3018f63127be189578 # v0.14.0
