name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "24 5 * * 0" # Once a week
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  analysis:
    name: Scorecard analysis
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.event.repository.fork == false)
    runs-on: ubuntu-24.04
    permissions:
      checks: read # Read CI results
      contents: read # Checkout the repository
      id-token: write # Publish Scorecard results with GitHub OIDC
      issues: read # Read issues
      pull-requests: read # Read pull requests
      security-events: write # Upload the SARIF results to code scanning
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload code scanning results
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: results.sarif
