name: pwsh-test

on:
  workflow_call:

permissions: {}

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  pwsh-test:
    name: Test PowerShell scripts (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os:
          # renovate: datasource=github-runners depType=github-runner
          - ubuntu-24.04
          # renovate: datasource=github-runners depType=github-runner
          - windows-2025

    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Run Pester tests
      shell: pwsh
      run: ./build/scripts/tests/RunTests.ps1

    - name: Upload code coverage
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      continue-on-error: true
      timeout-minutes: 5
      env:
        OS: ${{ matrix.os }}
      with:
        disable_search: true
        disable_telem: true
        env_vars: OS
        files: build/scripts/tests/coverage.xml
        flags: unittests-PowerShellScripts
        name: Code Coverage for PowerShell scripts on [${{ matrix.os }}]
        codecov_yml_path: .github/codecov.yml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results
      if: ${{ !cancelled() && hashFiles('build/scripts/tests/testResults.xml') != '' }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      continue-on-error: true
      timeout-minutes: 5
      env:
        OS: ${{ matrix.os }}
      with:
        disable_search: true
        disable_telem: true
        env_vars: OS
        files: build/scripts/tests/testResults.xml
        flags: unittests-PowerShellScripts
        name: Test results for PowerShell scripts on [${{ matrix.os }}]
        report_type: test_results
        token: ${{ secrets.CODECOV_TOKEN }}
