name: Lint - Spelling & Encoding

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-typos:
    name: Check for typos
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Check for typos
      uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0

  run-sanitycheck:
    name: Run sanity check
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Detect non-ASCII encoding and trailing space
      run: python3 ./build/scripts/sanitycheck.py
