name: Survey on Merged PR by Non-Member

on:
  pull_request_target:
    branches: [main]
    types: [closed]

permissions: {}

jobs:
  comment-on-pr:
    name: Add survey to PR if author is not a member
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    # Only run for merged pull requests by non-members
    if: |
      github.event.pull_request.merged &&
      (github.event.pull_request.author_association == 'CONTRIBUTOR' ||
       github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' ||
       github.event.pull_request.author_association == 'FIRST_TIMER')
    steps:
      - name: Add comment
        run: |
          gh pr comment "${PR_NUMBER}" --repo "${GITHUB_REPOSITORY}" --body "Thank you for your contribution @${USERNAME}! :tada: We would like to hear from you about your experience contributing to OpenTelemetry by taking a few minutes to fill out this [survey](${SURVEY_URL})."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SURVEY_URL: https://docs.google.com/forms/d/e/1FAIpQLSf2FfCsW-DimeWzdQgfl0KDzT2UEAqu69_f7F2BVPSxVae1cQ/viewform?entry.1540511742=open-telemetry/opentelemetry-dotnet
          USERNAME: ${{ github.event.pull_request.user.login }}
