name: Unreleased changes report

on:
  schedule:
  - cron: '0 8 * * 1'  # Every Monday at 08:00 UTC
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  report:
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.event.repository.fork == false)
    name: Generate unreleased changes report
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Generate unreleased changes report
      shell: pwsh
      run: .\build\scripts\report-unreleased-changes.ps1 >> ${env:GITHUB_STEP_SUMMARY}
