name: Publish & Verify AOT Compatibility

on:
  workflow_call:
    inputs:
      trigger:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run-verify-aot-compat:
    name: Verify AOT compatibility

    strategy:
      fail-fast: ${{ inputs.trigger == 'merge_group' }}
      matrix:
        os:
          # renovate: datasource=github-runners depType=github-runner
          - ubuntu-24.04
          # renovate: datasource=github-runners depType=github-runner
          - windows-2025
        version: [ net10.0, net11.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0

    - name: Publish AOT testApp, assert static analysis warning count, and run the app
      shell: pwsh
      run: .\build\scripts\test-aot-compatibility.ps1 ${env:TARGET_FRAMEWORK}
      env:
        TARGET_FRAMEWORK: ${{ matrix.version }}
