name: Publish & Verify AOT Compatibility

on:
  workflow_call:
    inputs:
      trigger:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run-verify-aot-compat:
    name: Verify AOT compatibility

    strategy:
      fail-fast: ${{ inputs.trigger == 'merge_group' }}
      matrix:
        os:
          # renovate: datasource=github-runners depType=github-runner
          - ubuntu-24.04
          # renovate: datasource=github-runners depType=github-runner
          - windows-2025
        version: [ net8.0, net9.0, net10.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

    - name: Publish AOT testApp, assert static analysis warning count, and run the app
      shell: pwsh
      run: .\build\scripts\test-aot-compatibility.ps1 ${env:TARGET_FRAMEWORK}
      env:
        TARGET_FRAMEWORK: ${{ matrix.version }}
