name: zizmor scan

on:
  pull_request:
  push:
    branches: [ 'main*' ]
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-24.04

    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: false

    permissions:
      actions: read # Scan GitHub Actions workflows
      contents: read # Checkout the repository
      security-events: write # Store results in the Security tab

    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Scan workflows with zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          persona: pedantic
