// <copyright file="ResourceSemanticConventions.cs" company="OpenTelemetry Authors">
// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>


// <auto-generated> This file has been auto generated from buildscripts/semantic-convention/templates/SemanticConventions.cs.j2</auto-generated>
namespace OpenTelemetry.Resources
{
    /// <summary>
    /// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
    /// <see href="https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md"/>.
    /// </summary>
    /// <remarks>
    /// Schema and specification version: https://opentelemetry.io/schemas/v1.7.0.
    /// </remarks>
    public static class ResourceSemanticConventions
    {
        /// <summary>
        /// Name of the cloud provider.
        /// </summary>
        public const string AttributeCloudProvider = "cloud.provider";

        /// <summary>
        /// The cloud account ID the resource is assigned to.
        /// </summary>
        public const string AttributeCloudAccountId = "cloud.account.id";

        /// <summary>
        /// The geographical region the resource is running. Refer to your provider's docs to see the available regions, for example <a href="https://www.alibabacloud.com/help/doc-detail/40654.htm">Alibaba Cloud regions</a>, <a href="https://aws.amazon.com/about-aws/global-infrastructure/regions_az/">AWS regions</a>, <a href="https://azure.microsoft.com/en-us/global-infrastructure/geographies/">Azure regions</a>, or <a href="https://cloud.google.com/about/locations">Google Cloud regions</a>.
        /// </summary>
        public const string AttributeCloudRegion = "cloud.region";

        /// <summary>
        /// Cloud regions often have multiple, isolated locations known as zones to increase availability. Availability zone represents the zone where the resource is running.
        /// </summary>
        /// <remarks>
        /// Availability zones are called "zones" on Alibaba Cloud and Google Cloud.
        /// </remarks>
        public const string AttributeCloudAvailabilityZone = "cloud.availability_zone";

        /// <summary>
        /// The cloud platform in use.
        /// </summary>
        /// <remarks>
        /// The prefix of the service SHOULD match the one specified in `cloud.provider`.
        /// </remarks>
        public const string AttributeCloudPlatform = "cloud.platform";

        /// <summary>
        /// The Amazon Resource Name (ARN) of an <a href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_instances.html">ECS container instance</a>.
        /// </summary>
        public const string AttributeAwsEcsContainerArn = "aws.ecs.container.arn";

        /// <summary>
        /// The ARN of an <a href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/clusters.html">ECS cluster</a>.
        /// </summary>
        public const string AttributeAwsEcsClusterArn = "aws.ecs.cluster.arn";

        /// <summary>
        /// The <a href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html">launch type</a> for an ECS task.
        /// </summary>
        public const string AttributeAwsEcsLaunchtype = "aws.ecs.launchtype";

        /// <summary>
        /// The ARN of an <a href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html">ECS task definition</a>.
        /// </summary>
        public const string AttributeAwsEcsTaskArn = "aws.ecs.task.arn";

        /// <summary>
        /// The task definition family this task definition is a member of.
        /// </summary>
        public const string AttributeAwsEcsTaskFamily = "aws.ecs.task.family";

        /// <summary>
        /// The revision for this task definition.
        /// </summary>
        public const string AttributeAwsEcsTaskRevision = "aws.ecs.task.revision";

        /// <summary>
        /// The ARN of an EKS cluster.
        /// </summary>
        public const string AttributeAwsEksClusterArn = "aws.eks.cluster.arn";

        /// <summary>
        /// The name(s) of the AWS log group(s) an application is writing to.
        /// </summary>
        /// <remarks>
        /// Multiple log groups must be supported for cases like multi-container applications, where a single application has sidecar containers, and each write to their own log group.
        /// </remarks>
        public const string AttributeAwsLogGroupNames = "aws.log.group.names";

        /// <summary>
        /// The Amazon Resource Name(s) (ARN) of the AWS log group(s).
        /// </summary>
        /// <remarks>
        /// See the [log group ARN format documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html#CWL_ARN_Format).
        /// </remarks>
        public const string AttributeAwsLogGroupArns = "aws.log.group.arns";

        /// <summary>
        /// The name(s) of the AWS log stream(s) an application is writing to.
        /// </summary>
        public const string AttributeAwsLogStreamNames = "aws.log.stream.names";

        /// <summary>
        /// The ARN(s) of the AWS log stream(s).
        /// </summary>
        /// <remarks>
        /// See the [log stream ARN format documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html#CWL_ARN_Format). One log group can contain several log streams, so these ARNs necessarily identify both a log group and a log stream.
        /// </remarks>
        public const string AttributeAwsLogStreamArns = "aws.log.stream.arns";

        /// <summary>
        /// Container name.
        /// </summary>
        public const string AttributeContainerName = "container.name";

        /// <summary>
        /// Container ID. Usually a UUID, as for example used to <a href="https://docs.docker.com/engine/reference/run/#container-identification">identify Docker containers</a>. The UUID might be abbreviated.
        /// </summary>
        public const string AttributeContainerId = "container.id";

        /// <summary>
        /// The container runtime managing this container.
        /// </summary>
        public const string AttributeContainerRuntime = "container.runtime";

        /// <summary>
        /// Name of the image the container was built on.
        /// </summary>
        public const string AttributeContainerImageName = "container.image.name";

        /// <summary>
        /// Container image tag.
        /// </summary>
        public const string AttributeContainerImageTag = "container.image.tag";

        /// <summary>
        /// Name of the <a href="https://en.wikipedia.org/wiki/Deployment_environment">deployment environment</a> (aka deployment tier).
        /// </summary>
        public const string AttributeDeploymentEnvironment = "deployment.environment";

        /// <summary>
        /// A unique identifier representing the device.
        /// </summary>
        /// <remarks>
        /// The device identifier MUST only be defined using the values outlined below. This value is not an advertising identifier and MUST NOT be used as such. On iOS (Swift or Objective-C), this value MUST be equal to the [vendor identifier](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor). On Android (Java or Kotlin), this value MUST be equal to the Firebase Installation ID or a globally unique UUID which is persisted across sessions in your application. More information can be found [here](https://developer.android.com/training/articles/user-data-ids) on best practices and exact implementation details. Caution should be taken when storing personal data or anything which can identify a user. GDPR and data protection laws may apply, ensure you do your own due diligence.
        /// </remarks>
        public const string AttributeDeviceId = "device.id";

        /// <summary>
        /// The model identifier for the device.
        /// </summary>
        /// <remarks>
        /// It's recommended this value represents a machine readable version of the model identifier rather than the market or consumer-friendly name of the device.
        /// </remarks>
        public const string AttributeDeviceModelIdentifier = "device.model.identifier";

        /// <summary>
        /// The marketing name for the device model.
        /// </summary>
        /// <remarks>
        /// It's recommended this value represents a human readable version of the device model rather than a machine readable alternative.
        /// </remarks>
        public const string AttributeDeviceModelName = "device.model.name";

        /// <summary>
        /// The name of the single function that this runtime instance executes.
        /// </summary>
        /// <remarks>
        /// This is the name of the function as configured/deployed on the FaaS platform and is usually different from the name of the callback function (which may be stored in the [`code.namespace`/`code.function`](../../trace/semantic_conventions/span-general.md#source-code-attributes) span attributes).
        /// </remarks>
        public const string AttributeFaasName = "faas.name";

        /// <summary>
        /// The unique ID of the single function that this runtime instance executes.
        /// </summary>
        /// <remarks>
        /// Depending on the cloud provider, use:
        ///
        /// * **AWS Lambda:** The function [ARN](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html).
        /// Take care not to use the "invoked ARN" directly but replace any
        /// [alias suffix](https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html) with the resolved function version, as the same runtime instance may be invokable with multiple
        /// different aliases.
        /// * **GCP:** The [URI of the resource](https://cloud.google.com/iam/docs/full-resource-names)
        /// * **Azure:** The [Fully Qualified Resource ID](https://docs.microsoft.com/en-us/rest/api/resources/resources/get-by-id).
        ///
        /// On some providers, it may not be possible to determine the full ID at startup,
        /// which is why this field cannot be made required. For example, on AWS the account ID
        /// part of the ARN is not available without calling another AWS API
        /// which may be deemed too slow for a short-running lambda function.
        /// As an alternative, consider setting `faas.id` as a span attribute instead.
        /// </remarks>
        public const string AttributeFaasId = "faas.id";

        /// <summary>
        /// The immutable version of the function being executed.
        /// </summary>
        /// <remarks>
        /// Depending on the cloud provider and platform, use:
        ///
        /// * **AWS Lambda:** The [function version](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html)
        ///  (an integer represented as a decimal string).
        /// * **Google Cloud Run:** The [revision](https://cloud.google.com/run/docs/managing/revisions)
        ///  (i.e., the function name plus the revision suffix).
        /// * **Google Cloud Functions:** The value of the
        ///  [`K_REVISION` environment variable](https://cloud.google.com/functions/docs/env-var#runtime_environment_variables_set_automatically).
        /// * **Azure Functions:** Not applicable. Do not set this attribute.
        /// </remarks>
        public const string AttributeFaasVersion = "faas.version";

        /// <summary>
        /// The execution environment ID as a string, that will be potentially reused for other invocations to the same function/function version.
        /// </summary>
        /// <remarks>
        /// * **AWS Lambda:** Use the (full) log stream name.
        /// </remarks>
        public const string AttributeFaasInstance = "faas.instance";

        /// <summary>
        /// The amount of memory available to the serverless function in MiB.
        /// </summary>
        /// <remarks>
        /// It's recommended to set this attribute since e.g. too little memory can easily stop a Java AWS Lambda function from working correctly. On AWS Lambda, the environment variable `AWS_LAMBDA_FUNCTION_MEMORY_SIZE` provides this information.
        /// </remarks>
        public const string AttributeFaasMaxMemory = "faas.max_memory";

        /// <summary>
        /// Unique host ID. For Cloud, this must be the instance_id assigned by the cloud provider.
        /// </summary>
        public const string AttributeHostId = "host.id";

        /// <summary>
        /// Name of the host. On Unix systems, it may contain what the hostname command returns, or the fully qualified hostname, or another name specified by the user.
        /// </summary>
        public const string AttributeHostName = "host.name";

        /// <summary>
        /// Type of host. For Cloud, this must be the machine type.
        /// </summary>
        public const string AttributeHostType = "host.type";

        /// <summary>
        /// The CPU architecture the host system is running on.
        /// </summary>
        public const string AttributeHostArch = "host.arch";

        /// <summary>
        /// Name of the VM image or OS install the host was instantiated from.
        /// </summary>
        public const string AttributeHostImageName = "host.image.name";

        /// <summary>
        /// VM image ID. For Cloud, this value is from the provider.
        /// </summary>
        public const string AttributeHostImageId = "host.image.id";

        /// <summary>
        /// The version string of the VM image as defined in <a href="README.md#version-attributes">Version Attributes</a>.
        /// </summary>
        public const string AttributeHostImageVersion = "host.image.version";

        /// <summary>
        /// The name of the cluster.
        /// </summary>
        public const string AttributeK8sClusterName = "k8s.cluster.name";

        /// <summary>
        /// The name of the Node.
        /// </summary>
        public const string AttributeK8sNodeName = "k8s.node.name";

        /// <summary>
        /// The UID of the Node.
        /// </summary>
        public const string AttributeK8sNodeUid = "k8s.node.uid";

        /// <summary>
        /// The name of the namespace that the pod is running in.
        /// </summary>
        public const string AttributeK8sNamespaceName = "k8s.namespace.name";

        /// <summary>
        /// The UID of the Pod.
        /// </summary>
        public const string AttributeK8sPodUid = "k8s.pod.uid";

        /// <summary>
        /// The name of the Pod.
        /// </summary>
        public const string AttributeK8sPodName = "k8s.pod.name";

        /// <summary>
        /// The name of the Container in a Pod template.
        /// </summary>
        public const string AttributeK8sContainerName = "k8s.container.name";

        /// <summary>
        /// The UID of the ReplicaSet.
        /// </summary>
        public const string AttributeK8sReplicasetUid = "k8s.replicaset.uid";

        /// <summary>
        /// The name of the ReplicaSet.
        /// </summary>
        public const string AttributeK8sReplicasetName = "k8s.replicaset.name";

        /// <summary>
        /// The UID of the Deployment.
        /// </summary>
        public const string AttributeK8sDeploymentUid = "k8s.deployment.uid";

        /// <summary>
        /// The name of the Deployment.
        /// </summary>
        public const string AttributeK8sDeploymentName = "k8s.deployment.name";

        /// <summary>
        /// The UID of the StatefulSet.
        /// </summary>
        public const string AttributeK8sStatefulsetUid = "k8s.statefulset.uid";

        /// <summary>
        /// The name of the StatefulSet.
        /// </summary>
        public const string AttributeK8sStatefulsetName = "k8s.statefulset.name";

        /// <summary>
        /// The UID of the DaemonSet.
        /// </summary>
        public const string AttributeK8sDaemonsetUid = "k8s.daemonset.uid";

        /// <summary>
        /// The name of the DaemonSet.
        /// </summary>
        public const string AttributeK8sDaemonsetName = "k8s.daemonset.name";

        /// <summary>
        /// The UID of the Job.
        /// </summary>
        public const string AttributeK8sJobUid = "k8s.job.uid";

        /// <summary>
        /// The name of the Job.
        /// </summary>
        public const string AttributeK8sJobName = "k8s.job.name";

        /// <summary>
        /// The UID of the CronJob.
        /// </summary>
        public const string AttributeK8sCronjobUid = "k8s.cronjob.uid";

        /// <summary>
        /// The name of the CronJob.
        /// </summary>
        public const string AttributeK8sCronjobName = "k8s.cronjob.name";

        /// <summary>
        /// The operating system type.
        /// </summary>
        public const string AttributeOsType = "os.type";

        /// <summary>
        /// Human readable (not intended to be parsed) OS version information, like e.g. reported by <c>ver</c> or <c>lsb_release -a</c> commands.
        /// </summary>
        public const string AttributeOsDescription = "os.description";

        /// <summary>
        /// Human readable operating system name.
        /// </summary>
        public const string AttributeOsName = "os.name";

        /// <summary>
        /// The version string of the operating system as defined in <a href="../../resource/semantic_conventions/README.md#version-attributes">Version Attributes</a>.
        /// </summary>
        public const string AttributeOsVersion = "os.version";

        /// <summary>
        /// Process identifier (PID).
        /// </summary>
        public const string AttributeProcessPid = "process.pid";

        /// <summary>
        /// The name of the process executable. On Linux based systems, can be set to the <c>Name</c> in <c>proc/[pid]/status</c>. On Windows, can be set to the base name of <c>GetProcessImageFileNameW</c>.
        /// </summary>
        public const string AttributeProcessExecutableName = "process.executable.name";

        /// <summary>
        /// The full path to the process executable. On Linux based systems, can be set to the target of <c>proc/[pid]/exe</c>. On Windows, can be set to the result of <c>GetProcessImageFileNameW</c>.
        /// </summary>
        public const string AttributeProcessExecutablePath = "process.executable.path";

        /// <summary>
        /// The command used to launch the process (i.e. the command name). On Linux based systems, can be set to the zeroth string in <c>proc/[pid]/cmdline</c>. On Windows, can be set to the first parameter extracted from <c>GetCommandLineW</c>.
        /// </summary>
        public const string AttributeProcessCommand = "process.command";

        /// <summary>
        /// The full command used to launch the process as a single string representing the full command. On Windows, can be set to the result of <c>GetCommandLineW</c>. Do not set this if you have to assemble it just for monitoring; use <c>process.command_args</c> instead.
        /// </summary>
        public const string AttributeProcessCommandLine = "process.command_line";

        /// <summary>
        /// All the command arguments (including the command/executable itself) as received by the process. On Linux-based systems (and some other Unixoid systems supporting procfs), can be set according to the list of null-delimited strings extracted from <c>proc/[pid]/cmdline</c>. For libc-based executables, this would be the full argv vector passed to <c>main</c>.
        /// </summary>
        public const string AttributeProcessCommandArgs = "process.command_args";

        /// <summary>
        /// The username of the user that owns the process.
        /// </summary>
        public const string AttributeProcessOwner = "process.owner";

        /// <summary>
        /// The name of the runtime of this process. For compiled native binaries, this SHOULD be the name of the compiler.
        /// </summary>
        public const string AttributeProcessRuntimeName = "process.runtime.name";

        /// <summary>
        /// The version of the runtime of this process, as returned by the runtime without modification.
        /// </summary>
        public const string AttributeProcessRuntimeVersion = "process.runtime.version";

        /// <summary>
        /// An additional description about the runtime of the process, for example a specific vendor customization of the runtime environment.
        /// </summary>
        public const string AttributeProcessRuntimeDescription = "process.runtime.description";

        /// <summary>
        /// Logical name of the service.
        /// </summary>
        /// <remarks>
        /// MUST be the same for all instances of horizontally scaled services. If the value was not specified, SDKs MUST fallback to `unknown_service:` concatenated with [`process.executable.name`](process.md#process), e.g. `unknown_service:bash`. If `process.executable.name` is not available, the value MUST be set to `unknown_service`.
        /// </remarks>
        public const string AttributeServiceName = "service.name";

        /// <summary>
        /// A namespace for <c>service.name</c>.
        /// </summary>
        /// <remarks>
        /// A string value having a meaning that helps to distinguish a group of services, for example the team name that owns a group of services. `service.name` is expected to be unique within the same namespace. If `service.namespace` is not specified in the Resource then `service.name` is expected to be unique for all services that have no explicit namespace defined (so the empty/unspecified namespace is simply one more valid namespace). Zero-length namespace string is assumed equal to unspecified namespace.
        /// </remarks>
        public const string AttributeServiceNamespace = "service.namespace";

        /// <summary>
        /// The string ID of the service instance.
        /// </summary>
        /// <remarks>
        /// MUST be unique for each instance of the same `service.namespace,service.name` pair (in other words `service.namespace,service.name,service.instance.id` triplet MUST be globally unique). The ID helps to distinguish instances of the same service that exist at the same time (e.g. instances of a horizontally scaled service). It is preferable for the ID to be persistent and stay the same for the lifetime of the service instance, however it is acceptable that the ID is ephemeral and changes during important lifetime events for the service (e.g. service restarts). If the service has no inherent unique ID that can be used as the value of this attribute it is recommended to generate a random Version 1 or Version 4 RFC 4122 UUID (services aiming for reproducible UUIDs may also use Version 5, see RFC 4122 for more recommendations).
        /// </remarks>
        public const string AttributeServiceInstanceId = "service.instance.id";

        /// <summary>
        /// The version string of the service API or implementation.
        /// </summary>
        public const string AttributeServiceVersion = "service.version";

        /// <summary>
        /// The name of the telemetry SDK as defined above.
        /// </summary>
        public const string AttributeTelemetrySdkName = "telemetry.sdk.name";

        /// <summary>
        /// The language of the telemetry SDK.
        /// </summary>
        public const string AttributeTelemetrySdkLanguage = "telemetry.sdk.language";

        /// <summary>
        /// The version string of the telemetry SDK.
        /// </summary>
        public const string AttributeTelemetrySdkVersion = "telemetry.sdk.version";

        /// <summary>
        /// The version string of the auto instrumentation agent, if used.
        /// </summary>
        public const string AttributeTelemetryAutoVersion = "telemetry.auto.version";

        /// <summary>
        /// The name of the web engine.
        /// </summary>
        public const string AttributeWebengineName = "webengine.name";

        /// <summary>
        /// The version of the web engine.
        /// </summary>
        public const string AttributeWebengineVersion = "webengine.version";

        /// <summary>
        /// Additional description of the web engine (e.g. detailed version and edition information).
        /// </summary>
        public const string AttributeWebengineDescription = "webengine.description";

        /// <summary>
        /// Prefix for 'cloud'.
        /// </summary>
        /// span
        public static readonly string PrefixCloud = "cloud";

        /// <summary>
        /// Prefix for 'aws.ecs'.
        /// </summary>
        /// span
        public static readonly string PrefixAwsEcs = "aws.ecs";

        /// <summary>
        /// Prefix for 'aws.eks'.
        /// </summary>
        /// span
        public static readonly string PrefixAwsEks = "aws.eks";

        /// <summary>
        /// Prefix for 'aws.log'.
        /// </summary>
        /// span
        public static readonly string PrefixAwsLog = "aws.log";

        /// <summary>
        /// Prefix for 'container'.
        /// </summary>
        /// span
        public static readonly string PrefixContainer = "container";

        /// <summary>
        /// Prefix for 'deployment'.
        /// </summary>
        /// span
        public static readonly string PrefixDeployment = "deployment";

        /// <summary>
        /// Prefix for 'device'.
        /// </summary>
        /// span
        public static readonly string PrefixDevice = "device";

        /// <summary>
        /// Prefix for 'faas_resource'.
        /// </summary>
        /// span
        public static readonly string PrefixFaasResource = "faas";

        /// <summary>
        /// Prefix for 'host'.
        /// </summary>
        /// span
        public static readonly string PrefixHost = "host";

        /// <summary>
        /// Prefix for 'k8s.cluster'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sCluster = "k8s.cluster";

        /// <summary>
        /// Prefix for 'k8s.node'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sNode = "k8s.node";

        /// <summary>
        /// Prefix for 'k8s.namespace'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sNamespace = "k8s.namespace";

        /// <summary>
        /// Prefix for 'k8s.pod'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sPod = "k8s.pod";

        /// <summary>
        /// Prefix for 'k8s.container'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sContainer = "k8s.container";

        /// <summary>
        /// Prefix for 'k8s.replicaset'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sReplicaset = "k8s.replicaset";

        /// <summary>
        /// Prefix for 'k8s.deployment'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sDeployment = "k8s.deployment";

        /// <summary>
        /// Prefix for 'k8s.statefulset'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sStatefulset = "k8s.statefulset";

        /// <summary>
        /// Prefix for 'k8s.daemonset'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sDaemonset = "k8s.daemonset";

        /// <summary>
        /// Prefix for 'k8s.job'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sJob = "k8s.job";

        /// <summary>
        /// Prefix for 'k8s.cronjob'.
        /// </summary>
        /// span
        public static readonly string PrefixK8sCronjob = "k8s.cronjob";

        /// <summary>
        /// Prefix for 'os'.
        /// </summary>
        /// span
        public static readonly string PrefixOs = "os";

        /// <summary>
        /// Prefix for 'process'.
        /// </summary>
        /// span
        public static readonly string PrefixProcess = "process";

        /// <summary>
        /// Prefix for 'process.runtime'.
        /// </summary>
        /// span
        public static readonly string PrefixProcessRuntime = "process.runtime";

        /// <summary>
        /// Prefix for 'service'.
        /// </summary>
        /// span
        public static readonly string PrefixService = "service";

        /// <summary>
        /// Prefix for 'telemetry'.
        /// </summary>
        /// span
        public static readonly string PrefixTelemetry = "telemetry";

        /// <summary>
        /// Prefix for 'webengine_resource'.
        /// </summary>
        /// span
        public static readonly string PrefixWebengineResource = "webengine";

        /// <summary>
        /// Name of the cloud provider.
        /// </summary>
        public static class CloudProviderValues
        {
            /// <summary>
            /// Alibaba Cloud.
            /// </summary>
            public const string AlibabaCloud = "alibaba_cloud";

            /// <summary>
            /// Amazon Web Services.
            /// </summary>
            public const string Aws = "aws";

            /// <summary>
            /// Microsoft Azure.
            /// </summary>
            public const string Azure = "azure";

            /// <summary>
            /// Google Cloud Platform.
            /// </summary>
            public const string Gcp = "gcp";
        }

        /// <summary>
        /// The cloud platform in use.
        /// </summary>
        public static class CloudPlatformValues
        {
            /// <summary>
            /// Alibaba Cloud Elastic Compute Service.
            /// </summary>
            public const string AlibabaCloudEcs = "alibaba_cloud_ecs";

            /// <summary>
            /// Alibaba Cloud Function Compute.
            /// </summary>
            public const string AlibabaCloudFc = "alibaba_cloud_fc";

            /// <summary>
            /// AWS Elastic Compute Cloud.
            /// </summary>
            public const string AwsEc2 = "aws_ec2";

            /// <summary>
            /// AWS Elastic Container Service.
            /// </summary>
            public const string AwsEcs = "aws_ecs";

            /// <summary>
            /// AWS Elastic Kubernetes Service.
            /// </summary>
            public const string AwsEks = "aws_eks";

            /// <summary>
            /// AWS Lambda.
            /// </summary>
            public const string AwsLambda = "aws_lambda";

            /// <summary>
            /// AWS Elastic Beanstalk.
            /// </summary>
            public const string AwsElasticBeanstalk = "aws_elastic_beanstalk";

            /// <summary>
            /// Azure Virtual Machines.
            /// </summary>
            public const string AzureVm = "azure_vm";

            /// <summary>
            /// Azure Container Instances.
            /// </summary>
            public const string AzureContainerInstances = "azure_container_instances";

            /// <summary>
            /// Azure Kubernetes Service.
            /// </summary>
            public const string AzureAks = "azure_aks";

            /// <summary>
            /// Azure Functions.
            /// </summary>
            public const string AzureFunctions = "azure_functions";

            /// <summary>
            /// Azure App Service.
            /// </summary>
            public const string AzureAppService = "azure_app_service";

            /// <summary>
            /// Google Cloud Compute Engine (GCE).
            /// </summary>
            public const string GcpComputeEngine = "gcp_compute_engine";

            /// <summary>
            /// Google Cloud Run.
            /// </summary>
            public const string GcpCloudRun = "gcp_cloud_run";

            /// <summary>
            /// Google Cloud Kubernetes Engine (GKE).
            /// </summary>
            public const string GcpKubernetesEngine = "gcp_kubernetes_engine";

            /// <summary>
            /// Google Cloud Functions (GCF).
            /// </summary>
            public const string GcpCloudFunctions = "gcp_cloud_functions";

            /// <summary>
            /// Google Cloud App Engine (GAE).
            /// </summary>
            public const string GcpAppEngine = "gcp_app_engine";
        }

        /// <summary>
        /// The <a href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html">launch type</a> for an ECS task.
        /// </summary>
        public static class AwsEcsLaunchtypeValues
        {
            /// <summary>
            /// ec2.
            /// </summary>
            public const string Ec2 = "ec2";

            /// <summary>
            /// fargate.
            /// </summary>
            public const string Fargate = "fargate";
        }

        /// <summary>
        /// The CPU architecture the host system is running on.
        /// </summary>
        public static class HostArchValues
        {
            /// <summary>
            /// AMD64.
            /// </summary>
            public const string Amd64 = "amd64";

            /// <summary>
            /// ARM32.
            /// </summary>
            public const string Arm32 = "arm32";

            /// <summary>
            /// ARM64.
            /// </summary>
            public const string Arm64 = "arm64";

            /// <summary>
            /// Itanium.
            /// </summary>
            public const string Ia64 = "ia64";

            /// <summary>
            /// 32-bit PowerPC.
            /// </summary>
            public const string Ppc32 = "ppc32";

            /// <summary>
            /// 64-bit PowerPC.
            /// </summary>
            public const string Ppc64 = "ppc64";

            /// <summary>
            /// 32-bit x86.
            /// </summary>
            public const string X86 = "x86";
        }

        /// <summary>
        /// The operating system type.
        /// </summary>
        public static class OsTypeValues
        {
            /// <summary>
            /// Microsoft Windows.
            /// </summary>
            public const string Windows = "windows";

            /// <summary>
            /// Linux.
            /// </summary>
            public const string Linux = "linux";

            /// <summary>
            /// Apple Darwin.
            /// </summary>
            public const string Darwin = "darwin";

            /// <summary>
            /// FreeBSD.
            /// </summary>
            public const string Freebsd = "freebsd";

            /// <summary>
            /// NetBSD.
            /// </summary>
            public const string Netbsd = "netbsd";

            /// <summary>
            /// OpenBSD.
            /// </summary>
            public const string Openbsd = "openbsd";

            /// <summary>
            /// DragonFly BSD.
            /// </summary>
            public const string Dragonflybsd = "dragonflybsd";

            /// <summary>
            /// HP-UX (Hewlett Packard Unix).
            /// </summary>
            public const string Hpux = "hpux";

            /// <summary>
            /// AIX (Advanced Interactive eXecutive).
            /// </summary>
            public const string Aix = "aix";

            /// <summary>
            /// Oracle Solaris.
            /// </summary>
            public const string Solaris = "solaris";

            /// <summary>
            /// IBM z/OS.
            /// </summary>
            public const string ZOs = "z_os";
        }

        /// <summary>
        /// The language of the telemetry SDK.
        /// </summary>
        public static class TelemetrySdkLanguageValues
        {
            /// <summary>
            /// cpp.
            /// </summary>
            public const string Cpp = "cpp";

            /// <summary>
            /// dotnet.
            /// </summary>
            public const string Dotnet = "dotnet";

            /// <summary>
            /// erlang.
            /// </summary>
            public const string Erlang = "erlang";

            /// <summary>
            /// go.
            /// </summary>
            public const string Go = "go";

            /// <summary>
            /// java.
            /// </summary>
            public const string Java = "java";

            /// <summary>
            /// nodejs.
            /// </summary>
            public const string Nodejs = "nodejs";

            /// <summary>
            /// php.
            /// </summary>
            public const string Php = "php";

            /// <summary>
            /// python.
            /// </summary>
            public const string Python = "python";

            /// <summary>
            /// ruby.
            /// </summary>
            public const string Ruby = "ruby";

            /// <summary>
            /// webjs.
            /// </summary>
            public const string Webjs = "webjs";
        }
    }
}
